apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: iz7mkf8kj-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/rhtap-qe:cceb08f5116b1bcf2fef770e78124d81b0dad9cd@sha256:513ca112afb77d6ba73c51e7152a62b063dc5bcdd66a0d2961b71ce9fc612544
          name: container-image
